# yaml-language-server: $schema=./util/config.schema.json

# webhook: ""
tasks:
  supertail:
    cmd: "tail"
    args: ["-f","/tmp/grominet"]
    numprocs: 1
    autostart: false
    autorestart: "unexpected"
    exitcodes:
      - 0
    stopsignal: TERM
    stdout: "/tmp/titi"
