// Code generated by "stringer --type ProcessStatus --trimprefix ProcessStatus"; DO NOT EDIT.

package taskmaster

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProcessStatusUnknown-0]
	_ = x[ProcessStatusRunning-1]
	_ = x[ProcessStatusExited-2]
	_ = x[ProcessStatusStopped-3]
	_ = x[ProcessStatusIdle-4]
	_ = x[ProcessStatusFailed-5]
}

const _ProcessStatus_name = "UnknownRunningExitedStoppedIdleFailed"

var _ProcessStatus_index = [...]uint8{0, 7, 14, 20, 27, 31, 37}

func (i ProcessStatus) String() string {
	if i < 0 || i >= ProcessStatus(len(_ProcessStatus_index)-1) {
		return "ProcessStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProcessStatus_name[_ProcessStatus_index[i]:_ProcessStatus_index[i+1]]
}
