# https://taskfile.dev

version: '3'

vars:
  OS: darwin

tasks:
  default:
    cmds:
      - task: build-taskmaster

  build-all:
    cmds:
      - task: build-taskmaster
      - task: build-bonus

  build-cmd:
    internal: true
    cmds:
      - GOOS={{.OS}} go build -o ./bin/{{.OS}}/{{.CMD}} ./cmd/{{.CMD}}

  build-taskmaster:
    cmds:
      - task: build-cmd
        vars:
          CMD: taskmaster
    sources:
      - ./*.go
      - ./cmd/taskmaster/*.go
      - ./term/*.go
      - ./util/*.go
    generates:
      - ./bin/{{.OS}}/taskmaster

  build-bonus:
    deps: [generate]
    cmds:
      - task: build-cmd
        vars:
          CMD: taskmasterctl
      - task: build-cmd
        vars:
          CMD: taskmasterd
    sources:
      - ./*.go
      - ./term/*.go
      - ./util/*.go
      - ./cmd/taskmasterctl/*.go
      - ./cmd/taskmasterd/*.go
    generates:
      - ./bin/{{.OS}}/taskmasterctl
      - ./bin/{{.OS}}/taskmasterd

  clean:
    cmds:
      - rm -rf ./bin

  generate:
    cmds:
      - go generate ./rpcservice.go
    sources:
      - ./rpcservice.go
    generates:
      - ./rpcservice_const.go

  container-build:
    cmds:
      - cmd: container build --tag taskmaster --file Dockerfile .
        platforms: [darwin]
      - cmd: docker build --tag taskmaster --file Dockerfile .
        platforms: [linux] 

  container-run:
    cmds:
      - cmd: container run --name my-taskmaster --rm taskmaster
        platforms: [darwin]
      - cmd: docker run --name my-taskmaster --rm -d taskmaster
        platforms: [linux] 
