# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build-taskmaster

  build-all:
    cmds:
      - task: build-taskmaster
      - task: build-bonus

  build-cmd:
    internal: true
    cmds:
      - go build -o ./bin/{{.CMD}} ./cmd/{{.CMD}}

  build-taskmaster:
    cmds:
      - task: build-cmd
        vars:
          CMD: taskmaster
    sources:
      - ./*.go
      - ./cmd/taskmaster/*.go
      - ./term/*.go
      - ./util/*.go
    generates:
      - ./bin/taskmaster

  build-bonus:
    deps: [generate]
    cmds:
      - task: build-cmd
        vars:
          CMD: taskmasterctl
      - task: build-cmd
        vars:
          CMD: taskmasterd
    sources:
      - ./*.go
      - ./term/*.go
      - ./util/*.go
      - ./cmd/taskmasterctl/*.go
      - ./cmd/taskmasterd/*.go
    generates:
      - ./bin/taskmasterctl
      - ./bin/taskmasterd

  clean:
    cmds:
      - rm -rf ./bin

  generate:
    cmds:
      - go generate ./rpcservice.go
    sources:
      - ./rpcservice.go
    generates:
      - ./rpcservice_const.go

  container-build:
    vars:
      ARGS: container build --tag taskmaster --file Dockerfile .
    cmds:
      - cmd: container {{.ARGS}}
        platforms: [darwin]
      - cmd: docker {{.ARGS}}
        platforms: [linux] 

  container-run:
    vars:
      ARGS: run --name taskmaster --rm -it taskmaster
    cmds:
      - cmd: container {{.ARGS}}
        platforms: [darwin]
      - cmd: docker {{.ARGS}}
        platforms: [linux] 

  container-exec:
    vars:
      ARGS: exec -it taskmaster bash
    cmds:
      - cmd: container {{.ARGS}}
        platforms: [darwin]
      - cmd: docker {{.ARGS}}
        platforms: [linux] 
